version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_sqlite
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scrap_fdata
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
           
    tty: true  
    restart: always


  app:
    build:
      context: .
      dockerfile: Dockerfile_app  
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    tty: true  
    environment:
      - MYSQL_DATABASE=scrap_fdata
      - MYSQL_HOST=db 
      - MYSQL_USER=app
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=app

